db:
  username: postgres
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 101
    second: 55
    third.value: Third

  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
spring.profiles.active: qa

logging:
  level:
    root: info
    org.springframework.jdbc.core: info
  file:
    name: alex.log
    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:52000/postgres
    username: post
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false